spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

bird:
  web:
    base-packages: com.bird.samples.controller
    ip-check:
      enable: true
      ip-list:
        - uri-pattern: /v1/*
          ips: 0.0.0.0/0
        - uri-pattern: /v2/*
          ips: 0.0.0.0/0