spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bird-demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: root
    password: bird123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  mapper-locations: classpath*:com/bird/samples/mapper/**/*.xml
  type-aliases-package: com.bird.samples.model*
  type-aliases-super-type: com.bird.service.common.model.IDO
  configuration:
    mapUnderscoreToCamelCase: false
  global-config:
    db-config:
      id-type: input
      logic-delete-value: 1
      logic-not-delete-value: 0

bird:
  web:
    base-packages: com.bird.samples.controller
    ip-check:
      enable: true
      ip-list:
        - uri-pattern: /v1/*
          ips: 0.0.0.0/0
        - uri-pattern: /v2/*
          ips: 0.0.0.0/0
  service:
    audit-meta-object: false
    optimistic-lock-check: true