spring:
  application:
    name: bird-java-samples
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bird-demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: root
    password: bird123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 12
    host: 10.10.128.128
    port: 6739
    password: ctredis6739
    timeout: 30000
  task:
    execution:
      thread-name-prefix: bird-task-
      pool:
        core-size: 8
        max-size: 20
        queue-capacity: 99999999
        allow-core-thread-timeout: true
        keep-alive: 60s
      shutdown:
        await-termination: true
        await-termination-period: 5s
    scheduling:
      thread-name-prefix: bird-schedule-
      pool:
        size: 2
  kafka:
    producer:
      clientId: ${spring.application.name}
      bootstrap-servers: localhost:9092
      value-serializer:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: ${spring.application.name}
  rabbitmq:
    host: 127.0.0.1 # RabbitMQ 服务的地址
    port: 5672 # RabbitMQ 服务的端口
    username: guest # RabbitMQ 服务的账号
    password: guest # RabbitMQ 服务的密码

mybatis-plus:
  mapper-locations: classpath*:com/bird/samples/mapper/**/*.xml
  type-aliases-package: com.bird.samples.model*
  type-aliases-super-type: com.bird.service.common.model.IDO
  configuration:
    mapUnderscoreToCamelCase: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: input
      logic-delete-value: 1
      logic-not-delete-value: 0

bird:
  web:
    base-packages: com.bird.samples.controller
    ip-check:
      enabled: true
      ip-list:
        - uri-pattern: /v1/*
          ips: 0.0.0.0/0
        - uri-pattern: /v2/*
          ips: 0.0.0.0/0
    body-read:
      enabled: true
  sso:
    client:
      cookie-name: Sso-Token
      host: http://127.0.0.1:8080
      server: http://127.0.0.1:8080
  trace:
    dispatcher:
      period: 30
    db-field:
      enabled: true
    request:
      trace-type: default
      url-patterns: /**,/api
      trace-headers: user-agent
  file:
    disk:
      upload-dir: /mnt/upload/
      url-prefix: https://xxx.com
  eventbus:
    handler:
      group: ${spring.application.name}
      scan-packages: com.bird.samples
      rocketmq:
        name-server: http://10.10.128.158:9876
        consume-thread-min: 20
        consume-thread-max: 20
        consume-timeout: 15
        delay-level-when-next-consume: 0
        message-model: clustering
    log:
      pool-size: 1
      daemon: true
      period: 20
      threshold: 100
      default-queue-size: 1024
      thread-name-pattern: event-log-%d
  lock:
    redis:
      key-prefix: "bird:lock:"
      key-expire: 60000
      retry-interval: 1000
      retry-expire: 60000



rocketmq:
  name-server: http://10.10.128.158:9876
  producer:
    group: ${spring.application.name}

